export const GET_INGREDIENTS_REQUEST = 'GET_INGREDIENTS_REQUEST' as const;
export const GET_INGREDIENTS_SUCCESS = 'GET_INGREDIENTS_SUCCESS' as const;
export const GET_INGREDIENTS_ERROR = 'GET_INGREDIENTS_ERROR' as const;
export const GET_INGREDIENTS_RESET = 'GET_INGREDIENTS_RESET' as const;
